namespace VideoStickerBot.Enums
{
    public enum BotState
    {
        DEFAULT,
        START,
        SETTINGS,
        ADD_VIDEO,
        ADD_VIDEO_DESCRIPTION,
        INLINE_QUERY,
        VIDEO_UPLOADED,
        VIEW_ALL_VIDEO,
        SORTING_SELECTED,
        INLINE_RESULT,
        REMOVE_VIDEO,
        REVIEW_VIDEOS,
        REVIEWER_REJECTED,
        REVIEWER_APROVED,
        STICKER_MANAGMENT,
        EDIT_DESCRIPTION,
        EDIT_HASHTAG,
        INPUT_NEW_DESCRIPTION,
        INPUT_NEW_HASHTAG,
        COMPILATION_VIEW,
        COMPILATION_BY_TEXT_QUERY_VIEW,
        HELP,
        FRESH,
        BEST
    }
}